//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkLang.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerId { get; set; }
        public Nullable<int> PlateNo { get; set; }
        public string Color { get; set; }
        public string TimeIn { get; set; }
        public string TimeOut { get; set; }
        public string CarModel { get; set; }
    }
}
